### ISSUE TITLE
SLOP2.2.3 - Unmodified - Industrial Foregoing: Dissolution Chamber - JEI Integration

### ISSUE THREAD

**Issue by robsl2314** [AllTheMods/SLOP2-slice-of-pie-2#26]
JEI crashes on recipes for Dissolution Chamber.

`[22:34:40] [Render thread/ERROR] [me.je.gu.re.RecipeLayout/]: Error caught from Recipe Category: com.buuz135.industrial.plugin.jei.category.DissolutionChamberCategory
java.lang.IllegalArgumentException: FluidStack value must not be empty. net.minecraftforge.fluids.FluidStack@7bb02e9 minecraft:empty
	at mezz.jei.util.ErrorUtil.checkNotEmpty(ErrorUtil.java:224) ~[jei:7.7.1.121] {re:classloading}
	at mezz.jei.plugins.vanilla.ingredients.fluid.FluidStackHelper.getWildcardId(FluidStackHelper.java:85) ~[jei:7.7.1.121] {re:classloading}
	at mezz.jei.plugins.vanilla.ingredients.fluid.FluidStackHelper.getWildcardId(FluidStackHelper.java:26) ~[jei:7.7.1.121] {re:classloading}
	at mezz.jei.ingredients.IngredientInformation.getUniqueIdsWithWildcard(IngredientInformation.java:63) ~[jei:7.7.1.121] {re:classloading}
	at mezz.jei.ingredients.IngredientBlacklistInternal.isIngredientBlacklistedByApi(IngredientBlacklistInternal.java:24) ~[jei:7.7.1.121] {re:classloading}
	at mezz.jei.ingredients.IngredientFilter.isIngredientVisible(IngredientFilter.java:424) ~[jei:7.7.1.121] {re:classloading}
	at mezz.jei.ingredients.IngredientFilter.isIngredientVisible(IngredientFilter.java:420) ~[jei:7.7.1.121] {re:classloading}
	at mezz.jei.ingredients.IngredientManager.isIngredientVisible(IngredientManager.java:256) ~[jei:7.7.1.121] {re:classloading}
	at mezz.jei.gui.ingredients.GuiIngredient.filterOutHidden(GuiIngredient.java:141) ~[jei:7.7.1.121] {re:classloading}
	at mezz.jei.gui.ingredients.GuiIngredient.set(GuiIngredient.java:123) ~[jei:7.7.1.121] {re:classloading}
	at mezz.jei.gui.ingredients.GuiIngredientGroup.set(GuiIngredientGroup.java:119) ~[jei:7.7.1.121] {re:classloading}
	at com.buuz135.industrial.plugin.jei.category.DissolutionChamberCategory.setRecipe(DissolutionChamberCategory.java:122) ~[industrialforegoing:3.2.14.5] {re:classloading}
	at com.buuz135.industrial.plugin.jei.category.DissolutionChamberCategory.setRecipe(DissolutionChamberCategory.java:54) ~[industrialforegoing:3.2.14.5] {re:classloading}
	at mezz.jei.gui.recipes.RecipeLayout.create(RecipeLayout.java:72) ~[jei:7.7.1.121] {re:classloading}
	at mezz.jei.gui.recipes.RecipeGuiLogic.getRecipeLayouts(RecipeGuiLogic.java:178) ~[jei:7.7.1.121] {re:classloading}
	at mezz.jei.gui.recipes.RecipeGuiLogic.getRecipeLayouts(RecipeGuiLogic.java:164) ~[jei:7.7.1.121] {re:classloading}
	at mezz.jei.gui.recipes.RecipesGui.updateLayout(RecipesGui.java:490) ~[jei:7.7.1.121] {re:classloading}
	at mezz.jei.gui.recipes.RecipesGui.onStateChange(RecipesGui.java:542) ~[jei:7.7.1.121] {re:classloading}
	at mezz.jei.gui.recipes.RecipeGuiLogic.setState(RecipeGuiLogic.java:107) ~[jei:7.7.1.121] {re:classloading}
	at mezz.jei.gui.recipes.RecipeGuiLogic.setFocus(RecipeGuiLogic.java:60) ~[jei:7.7.1.121] {re:classloading}
	at mezz.jei.gui.recipes.RecipesGui.show(RecipesGui.java:425) ~[jei:7.7.1.121] {re:classloading}
	at mezz.jei.input.click.ClickFocusHandler.handleMouseClickedFocus(ClickFocusHandler.java:44) ~[jei:7.7.1.121] {re:classloading}
	at mezz.jei.input.click.ClickFocusHandler.handleClick(ClickFocusHandler.java:30) ~[jei:7.7.1.121] {re:classloading}
	at mezz.jei.input.CombinedMouseHandler.handleClick(CombinedMouseHandler.java:49) ~[jei:7.7.1.121] {re:classloading}
	at mezz.jei.input.InputHandler.onGuiMouseEvent(InputHandler.java:153) ~[jei:7.7.1.121] {re:classloading}
	at mezz.jei.events.EventBusHelper.lambda$registerWeakListener$2(EventBusHelper.java:116) ~[jei:7.7.1.121] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.client.ForgeHooksClient.onGuiMouseReleasedPre(ForgeHooksClient.java:633) ~[forge:?] {re:classloading,re:mixin}
	at net.minecraft.client.MouseHelper.func_198027_a(MouseHelper.java:92) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:randompatches.mixins.json:client.keybindings.MouseHelperMixin,pl:mixin:APP:ftbchunks-common.mixins.json:MouseHandlerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.Screen.func_231153_a_(Screen.java:427) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:quark.mixins.json:client.ScreenMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:91) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:randompatches.mixins.json:client.keybindings.MouseHelperMixin,pl:mixin:APP:ftbchunks-common.mixins.json:MouseHandlerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.func_228030_c_(MouseHelper.java:181) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:randompatches.mixins.json:client.keybindings.MouseHelperMixin,pl:mixin:APP:ftbchunks-common.mixins.json:MouseHandlerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(SourceFile:94) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.MouseHelper.func_228028_b_(MouseHelper.java:180) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:randompatches.mixins.json:client.keybindings.MouseHelperMixin,pl:mixin:APP:ftbchunks-common.mixins.json:MouseHandlerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10] {}
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:102) ~[?:?] {re:classloading}
	at net.minecraft.client.MainWindow.func_227802_e_(MainWindow.java:305) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:kubejs-common.mixins.json:MainWindowMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:996) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:kubejs-common.mixins.json:MinecraftMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:kubejs-common.mixins.json:MinecraftMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[minecraft-1.16.5-client.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.2.2-launcher.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?] {}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:52) [ForgeWrapper-1.5.1.jar:1.5.1] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?] {}
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?] {}
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?] {}`

**Comment by MadWomen** [comment]
its a known issue and will be fixed next update, you can fix it now by upgrading or downgrading JEI.
